---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Remove default nginx configuration (symbolic link)
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx 

- name: Remove default nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Copy Nginx configuration template
  ansible.builtin.template:
    src: conf.j2
    dest: /etc/nginx/sites-available/kapsulekorp.conf 
    owner: root
    group: root
    mode: '0644'
    validate: 'sh -c "nginx -t && test -f %s"'  
  notify: Reload Nginx

- name: Activate the site (symlink sites-enabled -> sites-available)
  ansible.builtin.file:
    src: /etc/nginx/sites-available/kapsulekorp.conf
    dest: /etc/nginx/sites-enabled/kapsulekorp.conf
    state: link
  notify: Reload Nginx

- name: Créer le répertoire de l'application
  ansible.builtin.file:
    path: /var/www/kapsulekorp  
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'