$ANSIBLE_VAULT;1.1;AES256
62386434366436623630306164393930336332396438633339613234386331343566663363376430
6465343231393766313635316364303261336566353662370a343931333936656236356137623661
36343530313438616636653164376430613238643439366432373932343236393031393233353838
3038636566316137390a316365626431626334656333316639626338346663353632663736656364
30393565663330353864396539383235653865353338323538396538353465316630
