$ANSIBLE_VAULT;1.1;AES256
37663039393564303565363031396134326538386163363461353361353862653030633738616630
6263303963346264393335636639366663623962316230350a303265333833366564383865376135
64626562303462633166313135323663656537336233353138623639343964616430376639663733
3262333637363638370a333435616130373635623634646161363832613032393866633637303133
61303932366662343239366139666239373762663066343363653065323731613334336664303231
63346639616532646662313339643965353836326335636438313134346139373638653764336531
65323231633239316133303264366130326164666261376166373433336335373832363363353135
66363963643931633564393964616165376537616366363862653933656537373838646563643031
34353134663361613135623764363737393136353837316539313464343331656464376162323961
65396465323165383861663634643435313462326537623365636431303165376563373835646336
63633437623935303866653536303130653766653934613365643062663835336535366366353831
65366131323032636334623236306639336432633438346536313931366565313339616431373537
64646666346237653039333036326431343339666563333266613631363563613961393332373530
66666131383665323463353862633161313662303533353062396434306232636663353938343364
66326334646563656331626463643462366539353564346361633166306361303734383261373831
64353236313366393334373232343465326162363432323531396365336362323238646366313666
35316238333036346564626538613339303139653939313466393630393235373932303565336633
35343935666364393335636566393565313564343537306664353038663934346634636563336263
34663238396139653332353632623861643464373739313933643062623834613230333032336437
63383833623333333664623533366662366165306637303335643339303335613739326237653863
6437
