$ANSIBLE_VAULT;1.1;AES256
38346434646131663533383464393534363230653532303066346235663863333765383161336638
6239646134383566313631376636326630316463343037310a633931316335613263616265653031
39306262363436663765633132306637336632306637343639303833653366343633356339623836
3430633763376262640a346630366262363764383864333338663536323463656238643539383632
34316638356235346636373863343439363930396331336565313531633234636466613439373531
39613335343639333465363164313336363436393063373330353664353530386532656330356562
61356363666664393830323634613733343832613837343738626532663163343661306537653430
65393838316139636564386631643263323464356361633433316339393634303862616331353631
37383263616466333936306563656531393439356564643434626165646665376164653930633062
61636533393935313934643733353965323838333539616534376333383761643964616266323135
30346135616336326539323230353964323535643439373637326465333331343030353862613239
32353835373662363031376263653338633564633733613365343239353038653837623637663931
30373738376162366465646633366262646131666363313334343436356137643335306163613362
38643632393032336633326566653031313937303766653961353430636433313730616332326663
64613337666161363231353264323537643166336539323439376336333065333036386466383364
32316564633937393361
