$ANSIBLE_VAULT;1.1;AES256
66646638313236663839353836623464633564613561323064323531366631656361653034363136
3339336430656637616532326437386435633530356564660a353766346635353332346632333265
66666136363739336561323634396261333365613633316539666134383531383732613264656335
3032313161343562360a656564393533383866323336633863643538653738323831336338336363
35353963306332663563346230643738356632383937643131636165336263636161
