$ANSIBLE_VAULT;1.1;AES256
30313338393938336365393361383231623465313666363636373761653162323963373938333838
6262386537356535383162383863616237626165353337390a646362313861636634343861653564
36333431366532626137663463363662613135323639346364646132623762343439323663393638
3061623063316463330a633437396632316361303939613061366665313635366330333263626638
38383431333634653832333933333462303736386461373364313434386165376532646435323434
3132663663336536366462653638353635663135663233303064
