- name: Install MySql server and the dependencies
  apt:
    name: [ "mysql-server", "python3-mysqldb" ]
    state: present
    update_cache: yes

- name: Start and activate the MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure MySQL listens on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL    

- name: Verify if root can login without password
  command: mysql -uroot -e "SELECT 1"
  register: mysql_root_can_login_without_password
  failed_when: false
  changed_when: false

- name: Set a root password of MySQL (only for the first run)
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    check_implicit_admin: yes
  when: mysql_root_can_login_without_password.rc == 0

- name: Create /root/.my.cnf for MySQL for later logins
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: "0600"



- name: Create application database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create application user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

