$ANSIBLE_VAULT;1.1;AES256
63623637643066636336316535333666623030663531373239333938653465633335623435366531
6533376461326330366134616535303965653236616431320a316636623262646637616637646461
64653265626430383138373833363562666138343262306337633861653035393961623437636337
3130306430336336660a383631663262343562613938356137383965643464356436386234613432
31616563393930353964613764366539313539306438336132383062633766336539373037613336
3932353036376665646465316539353362616463396161353562
