$ANSIBLE_VAULT;1.1;AES256
39316235663832623238636565636639643633663430383433383531663166383037653763353863
6439643162633539303634393866303637613264386335340a353734626537313138356666393366
37653932393031643361313664373336303937383130306663326231343866396463666637383962
3037396261363765610a376130366434666536323732376337653236623133666166613936373764
31663364353731326234323763323232326431356561313361333837316434643263636431356231
35353335343235666237303737373630366133343131663035633233633932346631653962306565
37373665333534623064386562656238343635636166386364663864356564663839383337616237
65613263613837646432363366383337313966656562353133373637633365633430303834633566
37613939636563653262633637666566626336376234616130663735386262663132626635303563
61313364363934376339313265336564636664376435363532663838336661306631616163373863
32666634396537666237626239633439386339363530356331613539313362366439663266353837
37653330336462366238393636663338623130353730633535326665383637666536333766646635
39316461316363643734376639663833653434303764643738316163303334666539346531353163
63363238623662353731343034346463316633396261376630386432303865613463346535646166
65363366353539666639353861663866393530386165396635383739623332663030316466303361
66663163323264353165363764363030343833376131336461373661393330306534313462303633
62326638313231613965333936643262336361643730346539373862383134646134323062343164
38303833393463326164303063333262626664636566356432346139616264643861386431666264
35333266393635656434616236383939613934366638313562376531616437383832633364616232
36623734626430363436306435623433626331646463633033653139356330643734346661393466
6566
