$ANSIBLE_VAULT;1.1;AES256
32653263613237666630623938306432656666313032326666663734393532376638643464653137
6135333434636563636234363966623361656236653165320a653139373566396231633435393935
32363532366263623939373636396638656262313962363461313964666632613135623034333532
3635663735623061660a326666306661383136356361333737623930386533353564313531646132
35383031356236616630373363653535383532643361383833366238383761303761663461323862
36366266656565386537633565633062386430366130333936346232386235643736646230316161
36653262396635396436636236343463383735396265306632623565623338626138656638313230
31383662396264356466613062643961623734623839356134326530313463363038343139373261
30323133653831363339313134383633353565663533313630616564333030626262393933366234
66363730613939373936343661383437376532383965386464623530303264623338663461623833
61643332616232356166323461386162656335613739343037643735653634636162623331656633
35306130653439383262653263333237323638656532323065303932356533653761633838346237
31626662356133363339376232393136336235663337666438613863326536323139643836303861
35373061643166373032356433386530623836653264383331333566666335383662656665316132
62363233306633393663393963393562346237376138663134646137663434343033353338636365
65376438633163616562
