 

- name: Créer le répertoire de l'application (utilisé comme root par Nginx)
  ansible.builtin.file:
    path: /var/www/kapsulekorp
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Déploiement des fichiers sources de l'application PHP
  ansible.builtin.template:
    src: index.php.j2
    dest: /var/www/kapsulekorp/index.php   
    owner: www-data
    group: www-data
    mode: '0644'
  tags: deployment

- name: Fix PHP-FPM log permissions
  file:
    path: /var/log/php8.1-fpm.log
    owner: www-data
    group: www-data
    mode: '0664'
