$ANSIBLE_VAULT;1.1;AES256
32343966353132643133623663656439353863343862343437376535366230366262336135303863
6362636665646263396332363834306161626163376432630a633463653738653539633933386565
39633135316365306239363335323437313163363036633463303231373030636362626161326134
6166623061356530610a666137623436366339333531653266386635393035393534653330373233
39616236363765376662666461613839633631656666356262386461333332353931316132663433
6236306463343530326465353130373664623135633338313937
